module(
    name = "bzlmodrio-revlib",
    version = "2027.0.0-alpha-3",
)

bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_cc", version = "0.2.13")
bazel_dep(name = "rules_java", version = "8.16.1")
bazel_dep(name = "rules_bzlmodrio_toolchains", version = "2025-2")
bazel_dep(name = "rules_bzlmodrio_jdk", version = "17.0.12-7.bcr1")
bazel_dep(name = "bzlmodrio-allwpilib", version = "2027.0.0-alpha-6")
bazel_dep(name = "bzlmodrio-opencv", version = "2027.4.13.0-3")

setup_bzlmodrio_revlib_cpp_dependencies = use_extension("//:maven_cpp_deps.bzl", "setup_bzlmodrio_revlib_cpp_dependencies")
use_repo(
    setup_bzlmodrio_revlib_cpp_dependencies,
    "bazelrio_com_revrobotics_frc_revlib-cpp_headers",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxarm64",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxarm64static",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxsystemcore",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxsystemcorestatic",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxx86-64",
    "bazelrio_com_revrobotics_frc_revlib-cpp_linuxx86-64static",
    "bazelrio_com_revrobotics_frc_revlib-cpp_osxuniversal",
    "bazelrio_com_revrobotics_frc_revlib-cpp_osxuniversalstatic",
    "bazelrio_com_revrobotics_frc_revlib-cpp_windowsx86-64",
    "bazelrio_com_revrobotics_frc_revlib-cpp_windowsx86-64static",
    "bazelrio_com_revrobotics_frc_revlib-driver_headers",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxarm64",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxarm64static",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxsystemcore",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxsystemcorestatic",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxx86-64",
    "bazelrio_com_revrobotics_frc_revlib-driver_linuxx86-64static",
    "bazelrio_com_revrobotics_frc_revlib-driver_osxuniversal",
    "bazelrio_com_revrobotics_frc_revlib-driver_osxuniversalstatic",
    "bazelrio_com_revrobotics_frc_revlib-driver_windowsx86-64",
    "bazelrio_com_revrobotics_frc_revlib-driver_windowsx86-64static",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxarm64",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxarm64static",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxsystemcore",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxsystemcorestatic",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxx86-64",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_linuxx86-64static",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_osxuniversal",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_osxuniversalstatic",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_windowsx86-64",
    "bazelrio_com_revrobotics_frc_revlibbackenddriver_windowsx86-64static",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxarm64",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxarm64static",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxsystemcore",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxsystemcorestatic",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxx86-64",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_linuxx86-64static",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_osxuniversal",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_osxuniversalstatic",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_windowsx86-64",
    "bazelrio_com_revrobotics_frc_revlibwpibackenddriver_windowsx86-64static",
)

setup_bzlmodrio_revlib_java_dependencies = use_extension("//:maven_java_deps.bzl", "setup_bzlmodrio_revlib_java_dependencies")
use_repo(
    setup_bzlmodrio_revlib_java_dependencies,
    "com_revrobotics_frc_revlib_java",
)
